[Appearance]
color_scheme_path=/home/torvik/.local/share/color-schemes/DankMatugen.colors
custom_palette=true
icon_theme=Adwaita
standard_dialogs=default
style=Fusion

[Interface]
buttonbox_layout=0
menus_have_icons=true
toolbutton_style=4
[Fonts]
general="MesloLGS Nerd Font,11,-1,5,50,0,0,0,0,0"
fixed="MesloLGS Nerd Font,12,-1,5,50,0,0,0,0,0"
